[package]
name = "axum-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.2"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.214", features = ["derive"] }